import{a as S,S as v,i}from"./assets/vendor-DqB7j7Ix.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const q="https://pixabay.com/api/",E="50780112-993b28f3a55d0d18f65c2792c";async function f(t,o){const n={key:E,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await S.get(q,{params:n})).data}const m=document.querySelector(".gallery"),h=document.querySelector(".loader"),u=document.querySelector(".lm-btn"),B=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(t){const o=t.map(({webformatURL:n,largeImageURL:a,tags:e,likes:r,views:s,comments:b,downloads:w})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${n}" alt="${e}"/>
        </a>
        <div>
          <p>Likes: ${r}</p>
          <p>Views: ${s}</p>
          <p>Comments: ${b}</p>
          <p>Downloads: ${w}</p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",o),B.refresh()}function P(){m.innerHTML=""}function p(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}function L(){u.classList.remove("hidden")}function d(){u.classList.add("hidden")}const $=document.querySelector(".form");let l="",c=1;$.addEventListener("submit",M);u.addEventListener("click",O);async function M(t){if(t.preventDefault(),l=t.currentTarget.elements["search-text"].value.trim(),c=1,!l){i.warning({message:"Please enter a search query."});return}P(),d(),p();try{const o=await f(l,c);o.hits.length===0&&i.info({title:"Error!",message:"Sorry, there are no images matching your search query. Please try again!"}),y(o.hits),o.totalHits>15&&L()}catch{i.error({title:"Error!",message:"Failed to load images"})}finally{g()}}async function O(){c+=1,d(),p();try{const t=await f(l,c);y(t.hits),c*15>=t.totalHits?(d(),i.info({message:"We're sorry, but you've reached the end of search results."})):L(),x()}catch{i.error({message:"Loading error"})}finally{g()}}function x(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
